# Generated by Django 5.1.7 on 2025-03-18 20:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255, null=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                10,
                                message="The phone number must contain at least 10 characters.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                13,
                                message="The phone number must be a maximum of 13 characters.",
                            ),
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("birthday", models.DateField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
