# Generated by Django 5.1.7 on 2025-03-14 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='The phone number must contain at least 10 characters.'), django.core.validators.MaxLengthValidator(13, message='The phone number must be a maximum of 13 characters.')]),
        ),
    ]
