# Generated by Django 5.1.7 on 2025-03-16 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(to="tags.tag"),
        ),
        migrations.AlterField(
            model_name="note",
            name="description",
            field=models.CharField(max_length=150),
        ),
    ]
