# Generated by Django 5.1.7 on 2025-03-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_name_note_tags_alter_note_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="note",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
